const stateOptions = [
  { key: 1, value: "Andhra Pradesh", text: "Andhra Pradesh" },
  { key: 2, value: "Arunachal Pradesh", text: "Arunachal Pradesh" },
  { key: 3, value: "Assam", text: "Assam" },
  { key: 4, value: "Bihar", text: "Bihar" },
  { key: 5, value: "Chhattisgarh", text: " Chhattisgarh" },
  { key: 6, value: "Goa", text: "Goa" },
  { key: 7, value: "Gujarat", text: "Gujarat" },
  { key: 8, value: "Haryana", text: "Haryana" },
  { key: 9, value: "Himachal Pradesh", text: "Himachal Pradesh" },
  { key: 10, value: "Jharkhand", text: "Jharkhand" },
  { key: 11, value: "Karnataka", text: "Karnataka" },
  { key: 12, value: "Kerala", text: "Kerala" },
  { key: 13, value: "Madhya Pradesh", text: "Madhya Pradesh" },
  { key: 14, value: "Maharashtra", text: "Maharashtra" },
  { key: 15, value: "Manipur", text: "Manipur" },
  { key: 16, value: "Meghalaya", text: "Meghalaya" },
  { key: 17, value: "Mizoram", text: "Mizoram" },
  { key: 18, value: "Nagaland", text: "Nagaland" },
  { key: 19, value: "Odisha", text: "Odisha" },
  { key: 20, value: "Punjab", text: "Punjab" },
  { key: 21, value: "Rajasthan", text: "Rajasthan" },
  { key: 22, value: "Sikkim", text: "Sikkim" },
  { key: 23, value: "Tamil Nadu", text: "Tamil Nadu" },
  { key: 24, value: "Telangana", text: "Telangana" },
  { key: 25, value: "Uttar Pradesh", text: "Uttar Pradesh" },
  { key: 26, value: "Uttarakhand", text: "Uttarakhand" },
  { key: 27, value: "West Bengal", text: "West Bengal" },
  {
    key: 28,
    value: "Andaman and Nicobar Islands",
    text: "Andaman and Nicobar Islands",
  },
  { key: 29, value: "Chandigarh", text: "Chandigarh" },
  {
    key: 30,
    value: "Dadra & Nagar Haveli and Daman & Diu",
    text: "Dadra & Nagar Haveli and Daman & Diu",
  },
  { key: 31, value: "Delhi", text: "Delhi" },
  { key: 32, value: "Jammu and Kashmir", text: "Jammu and Kashmir" },
  { key: 33, value: "Lakshadweep", text: "Lakshadweep" },
  { key: 34, value: "Puducherry", text: "Puducherry" },
  { key: 35, value: "Ladakh", text: "Ladakh" },
];

export default stateOptions;
